# Generated by Django 5.2.1 on 2025-06-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField(blank=True)),
                ('release_year', models.IntegerField()),
                ('actors', models.CharField(max_length=500)),
                ('genres', models.CharField(max_length=500)),
                ('directors', models.CharField(max_length=500)),
                ('poster', models.ImageField(upload_to='posters/')),
            ],
        ),
    ]
