# Generated by Django 4.2.23 on 2025-06-21 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieImageRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_movies', models.JSONField()),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_recommendations', to='recommender.movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieImageEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.BinaryField()),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_embedding', to='recommender.movie')),
            ],
        ),
    ]
