# Generated by Django 5.2.4 on 2025-07-09 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0002_movieimagerecommendation_movieimageembedding"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieCollaboratorRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recommended_movies", models.JSONField()),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaboratour_recommendations",
                        to="recommender.movie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MovieGenreRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recommended_movies", models.JSONField()),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="genre_recommendations",
                        to="recommender.movie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MovieLdaEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("embedding", models.BinaryField()),
                (
                    "movie",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lda_embedding",
                        to="recommender.movie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MoviePlotRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recommended_movies", models.JSONField()),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plot_recommendations",
                        to="recommender.movie",
                    ),
                ),
            ],
        ),
    ]
